name: Build with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # 检出代码

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew embedProxyJar

      - name: Upload Artifact (可选)
        if: success()
        uses: actions/upload-artifact@v4  # 关键修改：v3 → v4
        with:
          name: output-jar
          path: build/libs/*.jar
